### Prueba Login
POST http://127.0.0.1:4000/api/login
Content-Type: application/json

{
    "usuario": "alec",
    "password": "123"
}

### 1. Prueba de obtener datos del juego
GET http://localhost:4000/api/juego/datos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDE3OTUxNjE4OWE2ZmViZTA0YWFlOSIsImlhdCI6MTc4MzEwMDMxMX0.hqXJqHNBLkUX4IUK7XVIFvW0xq6EUr8EL_Rr-kOPSgc

### 2. Prueba de consulta de progreso
GET http://localhost:4000/api/usuario/progreso
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDE3OTUxNjE4OWE2ZmViZTA0YWFlOSIsImlhdCI6MTc4MzEwMDMxMX0.hqXJqHNBLkUX4IUK7XVIFvW0xq6EUr8EL_Rr-kOPSgc

### 3. Prueba de completar narrativa
PATCH http://localhost:4000/api/usuario/narrativa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDE3OTUxNjE4OWE2ZmViZTA0YWFlOSIsImlhdCI6MTc4MzEwMDMxMX0.hqXJqHNBLkUX4IUK7XVIFvW0xq6EUr8EL_Rr-kOPSgc

### 4. Prueba de obtener elementos
GET http://localhost:4000/api/elementos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDE3OTUxNjE4OWE2ZmViZTA0YWFlOSIsImlhdCI6MTc4MzEwMDMxMX0.hqXJqHNBLkUX4IUK7XVIFvW0xq6EUr8EL_Rr-kOPSgc

### 5. Prueba de crear elemento
POST http://localhost:4000/api/nuevo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDE3OTUxNjE4OWE2ZmViZTA0YWFlOSIsImlhdCI6MTc4MzEwMDMxMX0.hqXJqHNBLkUX4IUK7XVIFvW0xq6EUr8EL_Rr-kOPSgc

{
    "name": "Nueva Elemento",
    "description": "Prueba de creación"
}

### 6. Prueba de borrar elemento
DELETE http://localhost:4000/api/elementos/ID_DEL_ELEMENTO
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNDE3OTUxNjE4OWE2ZmViZTA0YWFlOSIsImlhdCI6MTc4MzEwMDMxMX0.hqXJqHNBLkUX4IUK7XVIFvW0xq6EUr8EL_Rr-kOPSgc